-------------
--pharmacies-
-------------

DROP MATERIALIZED VIEW IF EXISTS pharmacies_point;
CREATE MATERIALIZED VIEW pharmacies_point AS 
 SELECT osm_id,
    amenity,
    name,
    tags -> 'short_name'::text AS short_name,
    tags -> 'official_name'::text AS official_name,
    tags -> 'alt_name'::text AS alt_name,
    tags -> 'old_name'::text AS old_name,
    operator,
    tags -> 'operator:type'::text AS "operator-type",
    tags -> 'dispensing'::text AS dispensing,
    tags -> 'emergency'::text AS emergency,
    tags -> 'capacity'::text AS capacity,
    tags -> 'wheelchair'::text AS wheelchair,
    tags -> 'social_facility'::text AS social_facility,
    tags -> 'ref:FR:FINESS'::text AS "ref-FR-FINESS",
    tags -> 'type:FR:FINESS'::text AS "type-FR-FINESS",
    tags -> 'ref:FR:NAF'::text AS "ref-FR-NAF",
    tags -> 'ref:FR:SIRET'::text AS "ref-FR-SIRET",
    tags -> 'website'::text AS website,
    tags -> 'contact:website'::text AS "contact-website",
    tags -> 'url'::text AS url,
    tags -> 'phone'::text AS phone,
    tags -> 'contact:phone'::text AS "contact-phone",
    tags -> 'fax'::text AS fax,
    tags -> 'contact:fax'::text AS "contact-fax",
    tags -> 'email'::text AS email,
    tags -> 'contact:email'::text AS "contact-email",
    "addr:housename" AS "addr-housename",
    "addr:housenumber" AS "addr-housenumber",
    tags -> 'addr:street'::text AS "addr-street",
    tags -> 'addr:city'::text AS "addr-city",
    tags -> 'addr:postcode'::text AS "addr-postcode",
    tags -> 'wikidata'::text AS wikidata,
    tags -> 'wikipedia'::text AS wikipedia,
    tags -> 'description'::text AS description,
    tags -> 'opening_hours'::text AS opening_hours,
    tags -> 'source'::text AS source,
    tags -> 'note'::text AS note,
    /*tags -> 'osm_uid'::text AS osm_uid,
    tags -> 'osm_user'::text AS osm_user,
    tags -> 'osm_changeset'::text AS osm_changeset,*/
    tags -> 'osm_version'::text AS osm_version,
    tags -> 'osm_timestamp'::text AS osm_timestamp,
    way AS "the_geom",
    '' AS "osm_original_geom",
    'node' AS "osm_type"
   FROM planet_osm_point
  WHERE amenity = 'pharmacy'::text
  UNION
  SELECT osm_id,
    amenity,
    name,
    tags -> 'short_name'::text AS short_name,
    tags -> 'official_name'::text AS official_name,
    tags -> 'alt_name'::text AS alt_name,
    tags -> 'old_name'::text AS old_name,
    operator,
    tags -> 'operator:type'::text AS "operator-type",
    tags -> 'dispensing'::text AS dispensing,
    tags -> 'emergency'::text AS emergency,
    tags -> 'capacity'::text AS capacity,
    tags -> 'wheelchair'::text AS wheelchair,
    tags -> 'social_facility'::text AS social_facility,
    tags -> 'ref:FR:FINESS'::text AS "ref-FR-FINESS",
    tags -> 'type:FR:FINESS'::text AS "type-FR-FINESS",
    tags -> 'ref:FR:NAF'::text AS "ref-FR-NAF",
    tags -> 'ref:FR:SIRET'::text AS "ref-FR-SIRET",
    tags -> 'website'::text AS website,
    tags -> 'contact:website'::text AS "contact-website",
    tags -> 'url'::text AS url,
    tags -> 'phone'::text AS phone,
    tags -> 'contact:phone'::text AS "contact-phone",
    tags -> 'fax'::text AS fax,
    tags -> 'contact:fax'::text AS "contact-fax",
    tags -> 'email'::text AS email,
    tags -> 'contact:email'::text AS "contact-email",
    "addr:housename" AS "addr-housename",
    "addr:housenumber" AS "addr-housenumber",
    tags -> 'addr:street'::text AS "addr-street",
    tags -> 'addr:city'::text AS "addr-city",
    tags -> 'addr:postcode'::text AS "addr-postcode",
    tags -> 'wikidata'::text AS wikidata,
    tags -> 'wikipedia'::text AS wikipedia,
    tags -> 'description'::text AS description,
    tags -> 'opening_hours'::text AS opening_hours,
    tags -> 'source'::text AS source,
    tags -> 'note'::text AS note,
    /*tags -> 'osm_uid'::text AS osm_uid,
    tags -> 'osm_user'::text AS osm_user,
    tags -> 'osm_changeset'::text AS osm_changeset,*/
    tags -> 'osm_version'::text AS osm_version,
    tags -> 'osm_timestamp'::text AS osm_timestamp,
    ST_Centroid(way) AS "the_geom",
    ST_AsEWKT(way) AS "osm_original_geom",
    'way' AS "osm_type"
   FROM planet_osm_polygon
  WHERE amenity = 'pharmacy'::text;