-----------
--police--
-----------

-- ! UNION DES POINTS ET DES POLYGONES --
DROP MATERIALIZED VIEW IF EXISTS police_point;
CREATE MATERIALIZED VIEW police_point AS 
	SELECT
		osm_id,
		amenity,
		name, 
		operator,
		tags->'ref:FR:GendarmerieNationale' AS "ref-FR-GendarmerieNationale",
		tags->'official_name' AS official_name,
		tags->'police:FR' AS "police-FR",
		tags->'seasonal' AS "seasonal",
		tags->'emergency' AS "emergency",
		military,
		office,
		tags->'phone' AS phone,
		tags->'contact:phone' AS "contact-phone",
		tags->'emergency_phone' AS "emergency_phone",
		tags->'fax' AS "fax",
		tags->'contact:fax' AS "contact-fax",
		tags->'email' as "email",
		tags->'contact:email' AS "contact-email",
		tags->'opening_hours' AS opening_hours,
		tags->'wheelchair' AS "wheelchair",
		tags->'short_name' AS short_name,
		tags->'alt_name' AS alt_name,
		tags->'old_name' AS old_name,
		tags->'operator:type' as "operator-type",		
		tags->'website' AS "website",
		tags->'contact:website' AS "contact-website",
		tags->'url' AS url,
		"addr:housename" AS "addr-housename",
		"addr:housenumber" AS "addr-housenumber",
		tags->'addr:street' AS "addr-street",
		tags->'addr:city' AS "addr-city",
		tags->'addr:postcode' AS "addr-postcode",
		tags->'addr:full' AS "addr-full",
		tags->'wikidata' as "wikidata",
		tags->'wikipedia' as "wikipedia",
		tags->'description' AS description,
		tags->'source' AS "source",
		tags->'note' AS "note",
		/*tags->'osm_user' AS "osm_user",
		tags->'osm_uid' AS "osm_uid",
		tags->'osm_changeset' AS "osm_changeset",*/
		tags->'osm_version' AS "osm_version",
		tags->'osm_timestamp' AS "osm_timestamp",
		way AS "the_geom",
		'' AS "osm_original_geom",
		'node' AS "osm_type"
	FROM planet_osm_point 
	WHERE amenity='police'
	UNION
	SELECT
		osm_id,
		amenity,
		name, 
		operator,
		tags->'ref:FR:GendarmerieNationale' AS "ref-FR-GendarmerieNationale",
		tags->'official_name' AS official_name,
		tags->'police:FR' AS "police-FR",
		tags->'seasonal' AS "seasonal",
		tags->'emergency' AS "emergency",
		military,
		office,
		tags->'phone' AS phone,
		tags->'contact:phone' AS "contact-phone",
		tags->'emergency_phone' AS "emergency_phone",
		tags->'fax' AS "fax",
		tags->'contact:fax' AS "contact-fax",
		tags->'email' as "email",
		tags->'contact:email' AS "contact-email",
		tags->'opening_hours' AS opening_hours,
		tags->'wheelchair' AS "wheelchair",
		tags->'short_name' AS short_name,
		tags->'alt_name' AS alt_name,
		tags->'old_name' AS old_name,
		tags->'operator:type' as "operator-type",		
		tags->'website' AS "website",
		tags->'contact:website' AS "contact-website",
		tags->'url' AS url,
		"addr:housename" AS "addr-housename",
		"addr:housenumber" AS "addr-housenumber",
		tags->'addr:street' AS "addr-street",
		tags->'addr:city' AS "addr-city",
		tags->'addr:postcode' AS "addr-postcode",
		tags->'addr:full' AS "addr-full",
		tags->'wikidata' as "wikidata",
		tags->'wikipedia' as "wikipedia",
		tags->'description' AS description,
		tags->'source' AS "source",
		tags->'note' AS "note",
		/*tags->'osm_user' AS "osm_user",
		tags->'osm_uid' AS "osm_uid",
		tags->'osm_changeset' AS "osm_changeset",*/
		tags->'osm_version' AS "osm_version",
		tags->'osm_timestamp' AS "osm_timestamp",
		ST_Centroid(way) AS "the_geom",
		ST_AsEWKT(way) AS "osm_original_geom",
		(CASE osm_id > 0 WHEN true THEN 'way' ELSE 'rel' END) AS "osm_type"
	FROM planet_osm_polygon 
	WHERE amenity='police';