---------
--shops--
---------

DROP MATERIALIZED VIEW IF EXISTS shops_point;
CREATE MATERIALIZED VIEW shops_point AS 
	SELECT
		osm_id,
		shop,
		name,
		tags->'short_name' AS short_name,
		tags->'alt_name' AS alt_name,
		operator,
		brand,
		tags->'opening_hours' AS opening_hours,
		tags->'wheelchair' AS "wheelchair",
		tags->'internet_access' AS "internet_access",
		tags->'origin' AS "origin",
		tags->'wholesale' AS "wholesale",
		tags->'second_hand' AS "second_hand",
		tags->'payment' AS "payment",
		tags->'ref:FR:NAF' AS "ref-FR-NAF",
		tags->'ref:FR:SIRET' AS "ref-FR-SIRET",
		tags->'website' AS "website",
		tags->'contact:website' AS "contact-website",
		tags->'url' AS url,
		tags->'phone' AS phone,
		tags->'contact:phone' AS "contact-phone",
		tags->'fax' AS "fax",
		tags->'contact:fax' AS "contact-fax",
		tags->'email' as "email",
		tags->'contact:email' AS "contact-email",
		"addr:housename" AS "addr-housename",
		"addr:housenumber" AS "addr-housenumber",
		tags->'addr:street' AS "addr-street",
		tags->'addr:city' AS "addr-city",
		tags->'addr:postcode' AS "addr-postcode",	
		tags->'description' AS description,
		tags->'source' AS "source",
		tags->'note' AS "note",
		/*tags->'osm_user' AS "osm_user",
		tags->'osm_uid' AS "osm_uid",
		tags->'osm_changeset' AS "osm_changeset",*/
		tags->'osm_version' AS "osm_version",
		tags->'osm_timestamp' AS "osm_timestamp",
		way AS "the_geom",
		'' AS "osm_original_geom",
		'node' AS "osm_type"
	FROM planet_osm_point 
	WHERE shop IS NOT NULL
	UNION
	SELECT
		osm_id,
		shop,
		name,
		tags->'short_name' AS short_name,
		tags->'alt_name' AS alt_name,
		operator,
		brand,
		tags->'opening_hours' AS opening_hours,
		tags->'wheelchair' AS "wheelchair",
		tags->'internet_access' AS "internet_access",
		tags->'origin' AS "origin",
		tags->'wholesale' AS "wholesale",
		tags->'second_hand' AS "second_hand",
		tags->'payment' AS "payment",
		tags->'ref:FR:NAF' AS "ref-FR-NAF",
		tags->'ref:FR:SIRET' AS "ref-FR-SIRET",
		tags->'website' AS "website",
		tags->'contact:website' AS "contact-website",
		tags->'url' AS url,
		tags->'phone' AS phone,
		tags->'contact:phone' AS "contact-phone",
		tags->'fax' AS "fax",
		tags->'contact:fax' AS "contact-fax",
		tags->'email' as "email",
		tags->'contact:email' AS "contact-email",
		"addr:housename" AS "addr-housename",
		"addr:housenumber" AS "addr-housenumber",
		tags->'addr:street' AS "addr-street",
		tags->'addr:city' AS "addr-city",
		tags->'addr:postcode' AS "addr-postcode",	
		tags->'description' AS description,
		tags->'source' AS "source",
		tags->'note' AS "note",
		/*tags->'osm_user' AS "osm_user",
		tags->'osm_uid' AS "osm_uid",
		tags->'osm_changeset' AS "osm_changeset",*/
		tags->'osm_version' AS "osm_version",
		tags->'osm_timestamp' AS "osm_timestamp",
		ST_Centroid(way) AS "the_geom",
		ST_AsEWKT(way) AS "osm_original_geom",
		'way' AS "osm_type"
	FROM planet_osm_polygon 
	WHERE shop IS NOT NULL;